// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIq_BzTwWPCeyrPDKj1AJ4-sAT3BKyR9E',
    appId: '1:112514955660:web:a5ed245b2eed48ffeafea9',
    messagingSenderId: '112514955660',
    projectId: 'flutterpos-faf67',
    authDomain: 'flutterpos-faf67.firebaseapp.com',
    databaseURL: 'https://flutterpos-faf67-default-rtdb.firebaseio.com',
    storageBucket: 'flutterpos-faf67.appspot.com',
    measurementId: 'G-88TR40WHCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSYdx-d4Bapc2QfoztCDxX1mVCxk1VFE',
    appId: '1:112514955660:android:2f45734c02076358eafea9',
    messagingSenderId: '112514955660',
    projectId: 'flutterpos-faf67',
    databaseURL: 'https://flutterpos-faf67-default-rtdb.firebaseio.com',
    storageBucket: 'flutterpos-faf67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDah7iEXZkSPNIZirqPTFsyQlAzcMmi1jI',
    appId: '1:112514955660:ios:f926d13a5cc86b08eafea9',
    messagingSenderId: '112514955660',
    projectId: 'flutterpos-faf67',
    databaseURL: 'https://flutterpos-faf67-default-rtdb.firebaseio.com',
    storageBucket: 'flutterpos-faf67.appspot.com',
    iosBundleId: 'br.com.marcelo.myTasks.myTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDah7iEXZkSPNIZirqPTFsyQlAzcMmi1jI',
    appId: '1:112514955660:ios:f926d13a5cc86b08eafea9',
    messagingSenderId: '112514955660',
    projectId: 'flutterpos-faf67',
    databaseURL: 'https://flutterpos-faf67-default-rtdb.firebaseio.com',
    storageBucket: 'flutterpos-faf67.appspot.com',
    iosBundleId: 'br.com.marcelo.myTasks.myTasks',
  );
}
